export const DEMO_PAPERS = [
  {
    id: 'attention',
    title: 'Attention Is All You Need',
    year: 2017,
    domain: 'NLP',
    description: 'Introduces the Transformer — self-attention replaces recurrence entirely.',
    pdfUrl: 'https://arxiv.org/pdf/1706.03762',
    presetContext: `I'm building a sequence-to-sequence model for code summarization. My current architecture uses a bidirectional LSTM encoder with an attention mechanism and an LSTM decoder. Performance degrades significantly on long input sequences (>200 tokens), and training is slow. I'm evaluating whether to migrate to a Transformer-based architecture and want to understand the tradeoffs in terms of parallelism, positional encoding, and multi-head attention for my use case.`,
  },
  {
    id: 'lora',
    title: 'LoRA: Low-Rank Adaptation',
    year: 2021,
    domain: 'LLM',
    description: 'Parameter-efficient fine-tuning via trainable low-rank weight updates.',
    pdfUrl: 'https://arxiv.org/pdf/2106.09685',
    presetContext: `I'm fine-tuning LLaMA-2 (7B parameters) for a domain-specific customer support classification task. Full fine-tuning requires 4× A100s and is prohibitively expensive for my budget. I have about 50,000 labeled examples and need to run multiple experiment iterations quickly. I'm interested in parameter-efficient methods that maintain base model quality while reducing GPU memory and training time.`,
  },
  {
    id: 'resnet',
    title: 'Deep Residual Learning',
    year: 2015,
    domain: 'Vision',
    description: 'Residual connections enable training of very deep CNNs without degradation.',
    pdfUrl: 'https://arxiv.org/pdf/1512.03385',
    presetContext: `I'm building an image classification pipeline for chest X-ray pathology detection (14 disease classes). My custom CNN currently has 12 layers and accuracy plateaus around 78% — deeper networks produce worse results due to vanishing gradients. I'm using PyTorch with standard cross-entropy loss, Adam optimizer, and standard data augmentation (flips, rotations). I want to understand how to train deeper architectures reliably.`,
  },
  {
    id: 'focal',
    title: 'Focal Loss for Dense Object Detection',
    year: 2017,
    domain: 'Training',
    description: 'Dynamically down-weights easy examples to focus training on hard negatives.',
    pdfUrl: 'https://arxiv.org/pdf/1708.02002',
    presetContext: `I'm building a transformer-based text classifier for medical notes using a BERT backbone with a classification head, fine-tuned on labeled EHR (electronic health record) data. My current challenge is handling class imbalance — rare diagnoses are heavily underrepresented (some classes have <50 examples vs >10,000 for common ones). I'm also experimenting with data augmentation strategies like synonym replacement and back-translation to address the imbalance.`,
  },
  {
    id: 'ppo',
    title: 'Proximal Policy Optimization',
    year: 2017,
    domain: 'RL',
    description: 'Stable, sample-efficient on-policy RL via clipped surrogate objectives.',
    pdfUrl: 'https://arxiv.org/pdf/1707.06347',
    presetContext: `I'm training a reinforcement learning agent for a continuous robotic arm control task (6-DOF manipulation). Currently using vanilla policy gradient (REINFORCE) with a baseline, but training is highly unstable — reward variance is large and performance collapses periodically. I'm using a Gaussian policy parameterized by a 3-layer MLP. I need a more stable on-policy algorithm that doesn't require environment model access and works with continuous action spaces.`,
  },
]
